In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('drive')

Mounted at drive

In [ ]:
path = "/content/drive/MyDrive/Pradeep_redpine/Documents/"
master_data= pd.read_csv(path + 'master_data.csv')

master_data.head()

          a         b         c         d  ...        aq        ar        as  label
0  0.759328  0.051102  0.050447  0.691667  ...  0.009824  8.935547  0.003691    109
1  0.901039  0.236481  0.234768  0.666667  ...  0.015067  7.910156  0.010668    109
2  0.881105  0.172121  0.164977  0.665000  ...  0.013072  9.741211  0.004527    109
3  0.849716  0.135928  0.135301  0.683333  ...  0.008889  9.301758  0.005885    109
4  0.825774  0.139097  0.128035  0.675000  ...  0.011704  9.448242  0.006146    109

[5 rows x 46 columns]

In [ ]:
X=master_data.iloc[:,0:46][0:].to_numpy()

y=master_data.iloc[:,-1][0:].to_numpy()
y=y.reshape(-1,1)

In [ ]:
# Splitting the dataset into the Training set and Test set
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
# Fitting Random Forest Regression to the Training set
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 300, random_state = 0)
regressor.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=300, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [ ]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [ ]:
# Evaluating the Algorithm
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.11369281045751589
Mean Squared Error: 0.12014128540304983
Root Mean Squared Error: 0.34661402943771596